apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp  # key:value 값은 아무거나 정해도 된다.
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
